[pytest]
norecursedirs = tests/load
addopts = -v --maxfail=3 --tb=short --alluredir=allure-results/json --strict-markers
testpaths = tests
python_files = test_*.py
pythonpath = .
markers =
    ui: UI automation tests
    api: API integration tests
    load: Load testing